config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'static_pages#home'
  resources :users
  resources :portfolios
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
    belongs_to :user
    default_scope -> { order(created_at: :desc) }
    validates :title, presence: true, length: {maximum:50}
    validates :description, presence: true, length: {maximum:255}
    VALID_URL_REGEX = /\A#{URI::regexp(%w(http https))}\z/
    validates :url, presence: true, format: { with: VALID_URL_REGEX }
    validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :portfolios, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [ :email, :name, :password, :password_confirmation ]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
  end

  def after_sign_up_path_for(resources)
    root_path
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
    def index
        @portfolios = Portfolio.paginate(page: params[:page], per_page: 5)
    end

    def new
        @portfolio = Portfolio.new
    end

    def create
        @portfolio = current_user.portfolios.build(portfolio_params)
        if @portfolio.save
            redirect_to root_path
        else
            render 'static_pages/home'
        end
    end

    private

        def portfolio_params
            params.require(:portfolio).permit(:title, :description, :url)
        end


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @portfolios = @user.portfolios.paginate(page: params[:page], per_page: 5)
  end

  def index
    @users = User.paginate(page: params[:page])
  end

  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
    # 引数で与えられたユーザーのGravatar画像を返す
    def gravatar_for(user, size: 80)
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
end

app/views/layouts/_header.html.erb
  <header class="navbar navbar-fixed-top navbar-inverse">
    <%= link_to "portfolio summary",  root_path , id:"logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "マイページ", user_path(id: current_user) %></li>
          <li><%= link_to "閲覧", portfolios_path%></li>
          <li><%= link_to "投稿", new_portfolio_path%></li>
          <li><%= link_to 'プロフィール変更', edit_user_registration_path %></li>
          <li><%= link_to "ユーザー一覧", users_path %></li>
          <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "閲覧", portfolios_path%></li>
          <li><%= link_to 'サインアップ', new_user_registration_path %></li>
          <li><%= link_to 'ログイン', new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
      <%= favicon_link_tag("icon/falling_star.ico") %>
    <title><%= yield(:title) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim'%>
  </head>
  <body>
    <%=  render 'layouts/header' %>
      <div class="container">
        <%= yield %>
      </div>
  </body>
</html>

app/views/portfolios/_portfolio.html.erb
<div class ="name_box">
  <%= link_to gravatar_for(portfolio.user, size: 50), portfolio.user %>
  <span class="name"><%= link_to portfolio.user.name, portfolio.user %></span>
</div>
<div class = "linkBox btn--orange btn--cubic btn--shadow">
  <a href=<%= portfolio.url%> class = "portfolio_url"></a>
  <li id="portfolio-<%= portfolio.id %>">
        <div class="box">
          <p class="title"><%= portfolio.title %></p>
          <p class="description"><%= portfolio.description %></p>
          <p class="timestamp">
            Posted <%= time_ago_in_words(portfolio.created_at) %> ago.
          </p>
        </div>
  </li>
</div>

app/views/portfolios/index.html.erb
<% if @portfolios.any? %>
    <div class = "paginate_box">
        <%= will_paginate @portfolios%>
    </div>
        <ol class="portfolios">
            <%= render @portfolios %>
        </ol>
    <div class = "paginate_box">
        <%= will_paginate @portfolios%>
    </div>
<% end %>

app/views/portfolios/new.html.erb
<% provide(:title, 'New Portfolio') %>
<h1>New Portfolio</h1>

<div class='row'>
    <div class = 'col-md-6 col-md-offset-3'>
        <%= form_with(model: @portfolio, local: true) do |f| %>
            <%= f.label :title %>
            <%= f.text_field :title %>

            <%= f.label :description %>
            <%= f.text_area :description %>

            <%= f.label :url %>
            <%= f.text_field :url %>

            <%= f.submit "Create portfolio", class: "btn btn-primary" %>
        <% end %>
    </div>
</div>

app/views/portfolios/show.html.erb
<%= @portfolio.title %>

app/views/static_pages/home.html.erb
<% provide(:title, "Portfolio summary") %>
<div class = "main bgimg">
    <div class="icon">
        <%= image_tag 'icon/falling_star.svg'%>
    </div>
    <h1 class = "Overview">IT業界未就職者のためのプラットフォーム</h1>
    <div class = "description_home">
        <p>Portfolioは、IT業界未就職の方のポートフォリオを集めたサイトです。
    閲覧だけならアカウントは不要ですが、自分のポートフォリオを提出するにはアカウントの作成とサインインが必要です。</p>
    </div>
    <div class="button">
        <%= link_to "閲覧", portfolios_path, class: "btn btn-lg btn-primary "%>
        <%= link_to "投稿する", new_user_registration_path, class: "btn btn-lg btn-primary "%>
    </div>
</div>

app/views/users/_user.html.erb
<li>
  <%= link_to user.name, user %>
</li>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>
<div class = "paginate_box">
<%= will_paginate %>
</div>

<ul class="users">
  <%= render @users %>
</ul>

<div class = "paginate_box">
<%= will_paginate %>
</div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<aside>
    <section class="user_info">
        <h1>
            <%= gravatar_for @user %>
            <%= @user.name%>
        </h1>
    </section>
</aside>
<% if @user.portfolios.any? %>
    <h3 class = "count">Portfolios (<%= @user.portfolios.count %>)</h3>
    <div class = "paginate_box">
        <%= will_paginate @portfolios%>
    </div>
    <ol class="portfolios">
        <%= render @portfolios %>
    </ol>
    <div class = "paginate_box">
        <%= will_paginate @portfolios%>
    </div>
<% end %>